//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.24 at 07:19:41 PM CEST 
//


package cz.cvut.novott16.freecite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="atitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="btitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="au" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="place" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="spage" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="pub" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="epage" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "atitle",
    "date",
    "btitle",
    "genre",
    "pages",
    "au",
    "place",
    "spage",
    "pub",
    "epage"
})
@XmlRootElement(name = "book")
public class Book {

    @XmlElement(required = true)
    protected String atitle;
    @XmlSchemaType(name = "unsignedShort")
    protected int date;
    @XmlElement(required = true)
    protected String btitle;
    @XmlElement(required = true)
    protected String genre;
    @XmlElement(required = true)
    protected String pages;
    @XmlElement(required = true)
    protected String au;
    @XmlElement(required = true)
    protected String place;
    @XmlSchemaType(name = "unsignedByte")
    protected short spage;
    @XmlElement(required = true)
    protected String pub;
    @XmlSchemaType(name = "unsignedByte")
    protected short epage;

    /**
     * Gets the value of the atitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAtitle() {
        return atitle;
    }

    /**
     * Sets the value of the atitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAtitle(String value) {
        this.atitle = value;
    }

    /**
     * Gets the value of the date property.
     * 
     */
    public int getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     */
    public void setDate(int value) {
        this.date = value;
    }

    /**
     * Gets the value of the btitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBtitle() {
        return btitle;
    }

    /**
     * Sets the value of the btitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBtitle(String value) {
        this.btitle = value;
    }

    /**
     * Gets the value of the genre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPages(String value) {
        this.pages = value;
    }

    /**
     * Gets the value of the au property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAu() {
        return au;
    }

    /**
     * Sets the value of the au property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAu(String value) {
        this.au = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

    /**
     * Gets the value of the spage property.
     * 
     */
    public short getSpage() {
        return spage;
    }

    /**
     * Sets the value of the spage property.
     * 
     */
    public void setSpage(short value) {
        this.spage = value;
    }

    /**
     * Gets the value of the pub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPub() {
        return pub;
    }

    /**
     * Sets the value of the pub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPub(String value) {
        this.pub = value;
    }

    /**
     * Gets the value of the epage property.
     * 
     */
    public short getEpage() {
        return epage;
    }

    /**
     * Sets the value of the epage property.
     * 
     */
    public void setEpage(short value) {
        this.epage = value;
    }

}
