//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.24 at 07:19:41 PM CEST 
//


package cz.cvut.novott16.freecite;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="citation">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="authors">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="booktitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                     &lt;element name="pages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *                     &lt;element name="raw_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                   &lt;attribute name="valid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{}context-objects"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "citationOrContextObjects"
})
@XmlRootElement(name = "citations")
public class Citations {

    @XmlElements({
        @XmlElement(name = "citation", type = Citations.Citation.class),
        @XmlElement(name = "context-objects", type = ContextObjects.class)
    })
    protected List<Object> citationOrContextObjects;

    /**
     * Gets the value of the citationOrContextObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the citationOrContextObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCitationOrContextObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Citations.Citation }
     * {@link ContextObjects }
     * 
     * 
     */
    public List<Object> getCitationOrContextObjects() {
        if (citationOrContextObjects == null) {
            citationOrContextObjects = new ArrayList<Object>();
        }
        return this.citationOrContextObjects;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="authors">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="booktitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pages" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
     *         &lt;element name="raw_string" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="valid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "authors",
        "title",
        "booktitle",
        "publisher",
        "location",
        "pages",
        "year",
        "rawString"
    })
    public static class Citation {

        @XmlElement(required = true)
        protected Citations.Citation.Authors authors;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String booktitle;
        protected String publisher;
        protected String location;
        @XmlElement(required = true)
        protected String pages;
        @XmlSchemaType(name = "unsignedShort")
        protected int year;
        @XmlElement(name = "raw_string", required = true)
        protected String rawString;
        @XmlAttribute(name = "valid", required = true)
        protected boolean valid;

        @Override
        public String toString() {
            return "Citation{" + "authors=" + authors.toString() + ", title=" + title + ", booktitle=" + booktitle + ", publisher=" + publisher + ", location=" + location + ", pages=" + pages + ", year=" + year + ", rawString=" + rawString + ", valid=" + valid + '}';
        }

        
        
        /**
         * Gets the value of the authors property.
         * 
         * @return
         *     possible object is
         *     {@link Citations.Citation.Authors }
         *     
         */
        public Citations.Citation.Authors getAuthors() {
            return authors;
        }

        /**
         * Sets the value of the authors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Citations.Citation.Authors }
         *     
         */
        public void setAuthors(Citations.Citation.Authors value) {
            this.authors = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the booktitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBooktitle() {
            return booktitle;
        }

        /**
         * Sets the value of the booktitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBooktitle(String value) {
            this.booktitle = value;
        }

        /**
         * Gets the value of the publisher property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPublisher() {
            return publisher;
        }

        /**
         * Sets the value of the publisher property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPublisher(String value) {
            this.publisher = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

        /**
         * Gets the value of the pages property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPages() {
            return pages;
        }

        /**
         * Sets the value of the pages property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPages(String value) {
            this.pages = value;
        }

        /**
         * Gets the value of the year property.
         * 
         */
        public int getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         */
        public void setYear(int value) {
            this.year = value;
        }

        /**
         * Gets the value of the rawString property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRawString() {
            return rawString;
        }

        /**
         * Sets the value of the rawString property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRawString(String value) {
            this.rawString = value;
        }

        /**
         * Gets the value of the valid property.
         * 
         */
        public boolean isValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         */
        public void setValid(boolean value) {
            this.valid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "author"
        
        })
        public static class Authors {

            @XmlElement(required = true)
            protected List<String> author;

            /**
             * Gets the value of the author property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the author property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getAuthor() {
                if (author == null) {
                    author = new ArrayList<String>();
                }
                return this.author;
            }

            @Override
            public String toString() {
                StringBuilder sb = new StringBuilder();
                if(author==null){
                    return "unknown";}else{
                for(String aut:author){
                sb.append(aut).append(", ");
                }
                sb.delete(sb.length()-2, sb.length()-1);
                return sb.toString();
            }}

        }

    }

}
